/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.faculty_system.Admin;

import com.mycompany.faculty_system.Components.CoursesRow;
import com.mycompany.faculty_system.Components.DepartmentsRow;
import com.mycompany.faculty_system.Model.Courses;
import com.mycompany.faculty_system.Model.DepartmentUI;
import com.mycompany.faculty_system.Model.Departments;
import com.mycompany.faculty_system.Model.UserUI;
import com.mycompany.faculty_system.Service.AdminService;
import com.mycompany.faculty_system.Service.CourseService;
import com.mycompany.faculty_system.Service.DepartmentService;
import com.mycompany.faculty_system.Service.InstructorService;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author reymo
 */
public class AdminManageCourse extends javax.swing.JPanel {
    private ArrayList<Courses> courseList;
    
    public AdminManageCourse() throws SQLException {
        initComponents();
        
        AdminService service = new AdminService();
        this.courseList = service.getCouresList();
        refreshInstructorList();
    }
public void refreshInstructorList() {

    jPanel3.removeAll();

    jPanel3.setLayout(
            new javax.swing.BoxLayout(
                    jPanel3,
                    javax.swing.BoxLayout.Y_AXIS
            )
    );

    for (Courses course : courseList) {

        CoursesRow row =
                new CoursesRow(
                        course,
                        courseList,
                        this::refreshInstructorList
                );

        row.setAlignmentX(LEFT_ALIGNMENT);

        jPanel3.add(row);

        jPanel3.add(
                javax.swing.Box.createRigidArea(
                        new java.awt.Dimension(0, 10)
                )
        );
    }

    jPanel3.revalidate();

    jPanel3.repaint();
}
public void refreshFilteredList(ArrayList<Courses> list) {

    jPanel3.removeAll();

    jPanel3.setLayout(
            new javax.swing.BoxLayout(
                    jPanel3,
                    javax.swing.BoxLayout.Y_AXIS
            )
    );

    for (Courses department : list) {

        CoursesRow row = new CoursesRow(
                department,
                courseList,
                this::refreshInstructorList
        );

        jPanel3.add(row);
        jPanel3.add(javax.swing.Box.createRigidArea(
                new java.awt.Dimension(0, 10)
        ));
    }

    jPanel3.revalidate();
    jPanel3.repaint();
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        search_txt = new javax.swing.JTextField();
        search_action = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        search_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        search_txt.addActionListener(this::search_txtActionPerformed);

        search_action.setBackground(new java.awt.Color(102, 255, 102));
        search_action.setText("Search");
        search_action.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_action.addActionListener(this::search_actionActionPerformed);

        jPanel7.setBackground(new java.awt.Color(102, 153, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(500, 120));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 13, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 153, 255));
        jPanel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ID");
        jPanel9.add(jLabel11);

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        jPanel10.setBackground(new java.awt.Color(102, 153, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("NAME");
        jPanel10.add(jLabel12);

        jPanel7.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 80, 30));

        jLabel14.setBackground(new java.awt.Color(153, 153, 153));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Manage Departments");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 770, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ACTIONS");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 200, 30));

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(search_action, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_action, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void search_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_txtActionPerformed

    private void search_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_actionActionPerformed
        // TODO add your handling code here:
            String keyword = search_txt.getText();

            ArrayList<Courses> filtered =
                    CourseService.searchCourse(courseList, keyword);

            refreshFilteredList(filtered);
    }//GEN-LAST:event_search_actionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton search_action;
    private javax.swing.JTextField search_txt;
    // End of variables declaration//GEN-END:variables

    public void setInstructor(UserUI instructor) {
        
    }
}
