/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.faculty_system;

import com.mycompany.faculty_system.Model.Departments;
import com.mycompany.faculty_system.Model.Roles;
import com.mycompany.faculty_system.Model.User;
import com.mycompany.faculty_system.Repository.UserRepository;
import com.mycompany.faculty_system.Service.ValidateUser;
import com.mycompany.faculty_system.Utilities.Alert;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author reymo
 */
public class InstructorRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructorRegistration.class.getName());

    /**
     * Creates new form Login_View
     */
    public InstructorRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UserEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        UserConfirmPassword = new javax.swing.JPasswordField();
        UserRole = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UserPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        UserFirstname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UserLastname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        error_message1 = new javax.swing.JLabel();
        error_message2 = new javax.swing.JLabel();
        error_message3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Email:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 230, 440, 24);

        UserEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        UserEmail.addActionListener(this::UserEmailActionPerformed);
        jPanel1.add(UserEmail);
        UserEmail.setBounds(40, 260, 410, 34);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 310, 440, 24);

        UserConfirmPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        UserConfirmPassword.addActionListener(this::UserConfirmPasswordActionPerformed);
        jPanel1.add(UserConfirmPassword);
        UserConfirmPassword.setBounds(40, 430, 410, 36);

        UserRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department", "SOIT", "SOED" }));
        UserRole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        UserRole.addActionListener(this::UserRoleActionPerformed);
        jPanel1.add(UserRole);
        UserRole.setBounds(40, 490, 410, 32);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTER");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, new java.awt.Color(0, 0, 102), java.awt.Color.darkGray));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 550, 130, 34);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Already have an account? Login here");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 590, 421, 30);

        error_message.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        error_message.setForeground(new java.awt.Color(255, 0, 51));
        error_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error_message);
        error_message.setBounds(514, 85, 365, 37);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(397, 73, 476, 0);

        UserPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        UserPassword.addActionListener(this::UserPasswordActionPerformed);
        jPanel1.add(UserPassword);
        UserPassword.setBounds(39, 340, 410, 36);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Confirm Password:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 400, 440, 24);

        UserFirstname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        jPanel1.add(UserFirstname);
        UserFirstname.setBounds(40, 100, 413, 34);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("First Name:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 70, 440, 24);

        UserLastname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        jPanel1.add(UserLastname);
        UserLastname.setBounds(40, 180, 413, 34);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Last Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(12, 150, 440, 24);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 180, 30, 34);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/email.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 260, 29, 34);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padlock.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 340, 24, 36);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/padlock.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 430, 24, 36);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 100, 30, 34);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("REGISTRATION");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 10, 460, 43);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("CLEAR");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.white, new java.awt.Color(0, 0, 102), java.awt.Color.darkGray));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 550, 130, 34);

        error_message1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        error_message1.setForeground(new java.awt.Color(255, 0, 51));
        error_message1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error_message1);
        error_message1.setBounds(0, 0, 0, 0);

        error_message2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        error_message2.setForeground(new java.awt.Color(255, 0, 51));
        error_message2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error_message2);
        error_message2.setBounds(0, 0, 0, 0);

        error_message3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        error_message3.setForeground(new java.awt.Color(255, 0, 51));
        error_message3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(error_message3);
        error_message3.setBounds(0, 0, 0, 0);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 470, 650));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 0));
        jPanel2.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-user.png"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel12);
        jLabel12.setBounds(190, 50, 130, 140);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Create Your Account");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 200, 490, 43);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Fill up the form to create a new account.");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel17);
        jLabel17.setBounds(120, 250, 280, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            UserFirstname.setText("");
            UserLastname.setText("");
            UserEmail.setText("");
            UserPassword.setText("");
            UserConfirmPassword.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPasswordActionPerformed

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String firstName = UserFirstname.getText();
            String lastName = UserLastname.getText();
            String email = UserEmail.getText();
            String password = UserPassword.getText();
            String confirmPassword = UserConfirmPassword.getText();

            String departmentName = UserRole.getSelectedItem().toString(); // rename for clarity

            if (!password.equals(confirmPassword)) {
                Alert.showError("Password and Confirm Password do not match");
                return;
            }

            Roles roles = new Roles();
            roles.setId(2); // better if dynamic later

            Departments department = new Departments();
            department.setName(departmentName);

            User user = new User();
            user.setFirstname(firstName);
            user.setLastname(lastName);
            user.setEmail(email);
            user.setPassword(password);
            user.setRoles(roles);
            user.setDepartments(department);

            UserRepository repo = new UserRepository();

            repo.addInstructor(user);

            UserFirstname.setText("");
            UserLastname.setText("");
            UserEmail.setText("");
            UserPassword.setText("");
            UserConfirmPassword.setText("");

        } catch (SQLException | IllegalArgumentException e) {
            Alert.showError(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UserRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserRoleActionPerformed

    private void UserConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserConfirmPasswordActionPerformed

    private void UserEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserEmailActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here
        this.dispose();
        Login_View login_view = new Login_View();
        
        login_view.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        login_view.pack();
        login_view.setLocationRelativeTo(null);
        login_view.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InstructorRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField UserConfirmPassword;
    private javax.swing.JTextField UserEmail;
    private javax.swing.JTextField UserFirstname;
    private javax.swing.JTextField UserLastname;
    private javax.swing.JPasswordField UserPassword;
    private javax.swing.JComboBox<String> UserRole;
    private javax.swing.JLabel error_message;
    private javax.swing.JLabel error_message1;
    private javax.swing.JLabel error_message2;
    private javax.swing.JLabel error_message3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
